Class {
	#name : 'RayKeyboardKey',
	#superclass : 'RayEnumeration',
	#classTraits : '{} + TraitedClass',
	#classVars : [
		'KEY_A',
		'KEY_APOSTROPHE',
		'KEY_B',
		'KEY_BACK',
		'KEY_BACKSLASH',
		'KEY_BACKSPACE',
		'KEY_C',
		'KEY_CAPS_LOCK',
		'KEY_COMMA',
		'KEY_D',
		'KEY_DELETE',
		'KEY_DOWN',
		'KEY_E',
		'KEY_EIGHT',
		'KEY_END',
		'KEY_ENTER',
		'KEY_EQUAL',
		'KEY_ESCAPE',
		'KEY_F',
		'KEY_F1',
		'KEY_F10',
		'KEY_F11',
		'KEY_F12',
		'KEY_F2',
		'KEY_F3',
		'KEY_F4',
		'KEY_F5',
		'KEY_F6',
		'KEY_F7',
		'KEY_F8',
		'KEY_F9',
		'KEY_FIVE',
		'KEY_FOUR',
		'KEY_G',
		'KEY_GRAVE',
		'KEY_H',
		'KEY_HOME',
		'KEY_I',
		'KEY_INSERT',
		'KEY_J',
		'KEY_K',
		'KEY_KB_MENU',
		'KEY_KP_0',
		'KEY_KP_1',
		'KEY_KP_2',
		'KEY_KP_3',
		'KEY_KP_4',
		'KEY_KP_5',
		'KEY_KP_6',
		'KEY_KP_7',
		'KEY_KP_8',
		'KEY_KP_9',
		'KEY_KP_ADD',
		'KEY_KP_DECIMAL',
		'KEY_KP_DIVIDE',
		'KEY_KP_ENTER',
		'KEY_KP_EQUAL',
		'KEY_KP_MULTIPLY',
		'KEY_KP_SUBTRACT',
		'KEY_L',
		'KEY_LEFT',
		'KEY_LEFT_ALT',
		'KEY_LEFT_BRACKET',
		'KEY_LEFT_CONTROL',
		'KEY_LEFT_SHIFT',
		'KEY_LEFT_SUPER',
		'KEY_M',
		'KEY_MENU',
		'KEY_MINUS',
		'KEY_N',
		'KEY_NINE',
		'KEY_NULL',
		'KEY_NUM_LOCK',
		'KEY_O',
		'KEY_ONE',
		'KEY_P',
		'KEY_PAGE_DOWN',
		'KEY_PAGE_UP',
		'KEY_PAUSE',
		'KEY_PERIOD',
		'KEY_PRINT_SCREEN',
		'KEY_Q',
		'KEY_R',
		'KEY_RIGHT',
		'KEY_RIGHT_ALT',
		'KEY_RIGHT_BRACKET',
		'KEY_RIGHT_CONTROL',
		'KEY_RIGHT_SHIFT',
		'KEY_RIGHT_SUPER',
		'KEY_S',
		'KEY_SCROLL_LOCK',
		'KEY_SEMICOLON',
		'KEY_SEVEN',
		'KEY_SIX',
		'KEY_SLASH',
		'KEY_SPACE',
		'KEY_T',
		'KEY_TAB',
		'KEY_THREE',
		'KEY_TWO',
		'KEY_U',
		'KEY_UP',
		'KEY_V',
		'KEY_VOLUME_DOWN',
		'KEY_VOLUME_UP',
		'KEY_W',
		'KEY_X',
		'KEY_Y',
		'KEY_Z',
		'KEY_ZERO'
	],
	#category : 'LibRaylib-Base',
	#package : 'LibRaylib',
	#tag : 'Base'
}

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_A [
	"This method was automatically generated"
	^ KEY_A
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_APOSTROPHE [
	"This method was automatically generated"
	^ KEY_APOSTROPHE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_B [
	"This method was automatically generated"
	^ KEY_B
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_BACK [
	"This method was automatically generated"
	^ KEY_BACK
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_BACKSLASH [
	"This method was automatically generated"
	^ KEY_BACKSLASH
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_BACKSPACE [
	"This method was automatically generated"
	^ KEY_BACKSPACE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_C [
	"This method was automatically generated"
	^ KEY_C
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_CAPS_LOCK [
	"This method was automatically generated"
	^ KEY_CAPS_LOCK
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_COMMA [
	"This method was automatically generated"
	^ KEY_COMMA
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_D [
	"This method was automatically generated"
	^ KEY_D
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_DELETE [
	"This method was automatically generated"
	^ KEY_DELETE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_DOWN [
	"This method was automatically generated"
	^ KEY_DOWN
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_E [
	"This method was automatically generated"
	^ KEY_E
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_EIGHT [
	"This method was automatically generated"
	^ KEY_EIGHT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_END [
	"This method was automatically generated"
	^ KEY_END
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_ENTER [
	"This method was automatically generated"
	^ KEY_ENTER
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_EQUAL [
	"This method was automatically generated"
	^ KEY_EQUAL
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_ESCAPE [
	"This method was automatically generated"
	^ KEY_ESCAPE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F [
	"This method was automatically generated"
	^ KEY_F
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F1 [
	"This method was automatically generated"
	^ KEY_F1
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F10 [
	"This method was automatically generated"
	^ KEY_F10
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F11 [
	"This method was automatically generated"
	^ KEY_F11
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F12 [
	"This method was automatically generated"
	^ KEY_F12
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F2 [
	"This method was automatically generated"
	^ KEY_F2
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F3 [
	"This method was automatically generated"
	^ KEY_F3
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F4 [
	"This method was automatically generated"
	^ KEY_F4
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F5 [
	"This method was automatically generated"
	^ KEY_F5
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F6 [
	"This method was automatically generated"
	^ KEY_F6
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F7 [
	"This method was automatically generated"
	^ KEY_F7
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F8 [
	"This method was automatically generated"
	^ KEY_F8
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_F9 [
	"This method was automatically generated"
	^ KEY_F9
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_FIVE [
	"This method was automatically generated"
	^ KEY_FIVE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_FOUR [
	"This method was automatically generated"
	^ KEY_FOUR
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_G [
	"This method was automatically generated"
	^ KEY_G
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_GRAVE [
	"This method was automatically generated"
	^ KEY_GRAVE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_H [
	"This method was automatically generated"
	^ KEY_H
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_HOME [
	"This method was automatically generated"
	^ KEY_HOME
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_I [
	"This method was automatically generated"
	^ KEY_I
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_INSERT [
	"This method was automatically generated"
	^ KEY_INSERT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_J [
	"This method was automatically generated"
	^ KEY_J
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_K [
	"This method was automatically generated"
	^ KEY_K
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KB_MENU [
	"This method was automatically generated"
	^ KEY_KB_MENU
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_0 [
	"This method was automatically generated"
	^ KEY_KP_0
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_1 [
	"This method was automatically generated"
	^ KEY_KP_1
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_2 [
	"This method was automatically generated"
	^ KEY_KP_2
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_3 [
	"This method was automatically generated"
	^ KEY_KP_3
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_4 [
	"This method was automatically generated"
	^ KEY_KP_4
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_5 [
	"This method was automatically generated"
	^ KEY_KP_5
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_6 [
	"This method was automatically generated"
	^ KEY_KP_6
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_7 [
	"This method was automatically generated"
	^ KEY_KP_7
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_8 [
	"This method was automatically generated"
	^ KEY_KP_8
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_9 [
	"This method was automatically generated"
	^ KEY_KP_9
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_ADD [
	"This method was automatically generated"
	^ KEY_KP_ADD
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_DECIMAL [
	"This method was automatically generated"
	^ KEY_KP_DECIMAL
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_DIVIDE [
	"This method was automatically generated"
	^ KEY_KP_DIVIDE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_ENTER [
	"This method was automatically generated"
	^ KEY_KP_ENTER
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_EQUAL [
	"This method was automatically generated"
	^ KEY_KP_EQUAL
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_MULTIPLY [
	"This method was automatically generated"
	^ KEY_KP_MULTIPLY
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_KP_SUBTRACT [
	"This method was automatically generated"
	^ KEY_KP_SUBTRACT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_L [
	"This method was automatically generated"
	^ KEY_L
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_LEFT [
	"This method was automatically generated"
	^ KEY_LEFT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_LEFT_ALT [
	"This method was automatically generated"
	^ KEY_LEFT_ALT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_LEFT_BRACKET [
	"This method was automatically generated"
	^ KEY_LEFT_BRACKET
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_LEFT_CONTROL [
	"This method was automatically generated"
	^ KEY_LEFT_CONTROL
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_LEFT_SHIFT [
	"This method was automatically generated"
	^ KEY_LEFT_SHIFT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_LEFT_SUPER [
	"This method was automatically generated"
	^ KEY_LEFT_SUPER
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_M [
	"This method was automatically generated"
	^ KEY_M
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_MENU [
	"This method was automatically generated"
	^ KEY_MENU
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_MINUS [
	"This method was automatically generated"
	^ KEY_MINUS
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_N [
	"This method was automatically generated"
	^ KEY_N
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_NINE [
	"This method was automatically generated"
	^ KEY_NINE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_NULL [
	"This method was automatically generated"
	^ KEY_NULL
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_NUM_LOCK [
	"This method was automatically generated"
	^ KEY_NUM_LOCK
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_O [
	"This method was automatically generated"
	^ KEY_O
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_ONE [
	"This method was automatically generated"
	^ KEY_ONE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_P [
	"This method was automatically generated"
	^ KEY_P
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_PAGE_DOWN [
	"This method was automatically generated"
	^ KEY_PAGE_DOWN
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_PAGE_UP [
	"This method was automatically generated"
	^ KEY_PAGE_UP
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_PAUSE [
	"This method was automatically generated"
	^ KEY_PAUSE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_PERIOD [
	"This method was automatically generated"
	^ KEY_PERIOD
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_PRINT_SCREEN [
	"This method was automatically generated"
	^ KEY_PRINT_SCREEN
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_Q [
	"This method was automatically generated"
	^ KEY_Q
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_R [
	"This method was automatically generated"
	^ KEY_R
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_RIGHT [
	"This method was automatically generated"
	^ KEY_RIGHT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_RIGHT_ALT [
	"This method was automatically generated"
	^ KEY_RIGHT_ALT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_RIGHT_BRACKET [
	"This method was automatically generated"
	^ KEY_RIGHT_BRACKET
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_RIGHT_CONTROL [
	"This method was automatically generated"
	^ KEY_RIGHT_CONTROL
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_RIGHT_SHIFT [
	"This method was automatically generated"
	^ KEY_RIGHT_SHIFT
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_RIGHT_SUPER [
	"This method was automatically generated"
	^ KEY_RIGHT_SUPER
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_S [
	"This method was automatically generated"
	^ KEY_S
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_SCROLL_LOCK [
	"This method was automatically generated"
	^ KEY_SCROLL_LOCK
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_SEMICOLON [
	"This method was automatically generated"
	^ KEY_SEMICOLON
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_SEVEN [
	"This method was automatically generated"
	^ KEY_SEVEN
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_SIX [
	"This method was automatically generated"
	^ KEY_SIX
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_SLASH [
	"This method was automatically generated"
	^ KEY_SLASH
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_SPACE [
	"This method was automatically generated"
	^ KEY_SPACE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_T [
	"This method was automatically generated"
	^ KEY_T
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_TAB [
	"This method was automatically generated"
	^ KEY_TAB
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_THREE [
	"This method was automatically generated"
	^ KEY_THREE
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_TWO [
	"This method was automatically generated"
	^ KEY_TWO
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_U [
	"This method was automatically generated"
	^ KEY_U
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_UP [
	"This method was automatically generated"
	^ KEY_UP
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_V [
	"This method was automatically generated"
	^ KEY_V
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_VOLUME_DOWN [
	"This method was automatically generated"
	^ KEY_VOLUME_DOWN
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_VOLUME_UP [
	"This method was automatically generated"
	^ KEY_VOLUME_UP
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_W [
	"This method was automatically generated"
	^ KEY_W
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_X [
	"This method was automatically generated"
	^ KEY_X
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_Y [
	"This method was automatically generated"
	^ KEY_Y
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_Z [
	"This method was automatically generated"
	^ KEY_Z
]

{ #category : 'accessing enum' }
RayKeyboardKey class >> KEY_ZERO [
	"This method was automatically generated"
	^ KEY_ZERO
]

{ #category : 'enum declaration' }
RayKeyboardKey class >> enumDecl [

	^ #(
	KEY_NULL 0
	KEY_APOSTROPHE 39
	KEY_COMMA 44
	KEY_MINUS 45
	KEY_PERIOD 46
	KEY_SLASH 47
	KEY_ZERO 48
	KEY_ONE 49
	KEY_TWO 50
	KEY_THREE 51
	KEY_FOUR 52
	KEY_FIVE 53
	KEY_SIX 54
	KEY_SEVEN 55
	KEY_EIGHT 56
	KEY_NINE 57
	KEY_SEMICOLON 59
	KEY_EQUAL 61
	KEY_A 65
	KEY_B 66
	KEY_C 67
	KEY_D 68
	KEY_E 69
	KEY_F 70
	KEY_G 71
	KEY_H 72
	KEY_I 73
	KEY_J 74
	KEY_K 75
	KEY_L 76
	KEY_M 77
	KEY_N 78
	KEY_O 79
	KEY_P 80
	KEY_Q 81
	KEY_R 82
	KEY_S 83
	KEY_T 84
	KEY_U 85
	KEY_V 86
	KEY_W 87
	KEY_X 88
	KEY_Y 89
	KEY_Z 90
	KEY_LEFT_BRACKET 91
	KEY_BACKSLASH 92
	KEY_RIGHT_BRACKET 93
	KEY_GRAVE 96
	KEY_SPACE 32
	KEY_ESCAPE 256
	KEY_ENTER 257
	KEY_TAB 258
	KEY_BACKSPACE 259
	KEY_INSERT 260
	KEY_DELETE 261
	KEY_RIGHT 262
	KEY_LEFT 263
	KEY_DOWN 264
	KEY_UP 265
	KEY_PAGE_UP 266
	KEY_PAGE_DOWN 267
	KEY_HOME 268
	KEY_END 269
	KEY_CAPS_LOCK 280
	KEY_SCROLL_LOCK 281
	KEY_NUM_LOCK 282
	KEY_PRINT_SCREEN 283
	KEY_PAUSE 284
	KEY_F1 290
	KEY_F2 291
	KEY_F3 292
	KEY_F4 293
	KEY_F5 294
	KEY_F6 295
	KEY_F7 296
	KEY_F8 297
	KEY_F9 298
	KEY_F10 299
	KEY_F11 300
	KEY_F12 301
	KEY_LEFT_SHIFT 340
	KEY_LEFT_CONTROL 341
	KEY_LEFT_ALT 342
	KEY_LEFT_SUPER 343
	KEY_RIGHT_SHIFT 344
	KEY_RIGHT_CONTROL 345
	KEY_RIGHT_ALT 346
	KEY_RIGHT_SUPER 347
	KEY_KB_MENU 348
	KEY_KP_0 320
	KEY_KP_1 321
	KEY_KP_2 322
	KEY_KP_3 323
	KEY_KP_4 324
	KEY_KP_5 325
	KEY_KP_6 326
	KEY_KP_7 327
	KEY_KP_8 328
	KEY_KP_9 329
	KEY_KP_DECIMAL 330
	KEY_KP_DIVIDE 331
	KEY_KP_MULTIPLY 332
	KEY_KP_SUBTRACT 333
	KEY_KP_ADD 334
	KEY_KP_ENTER 335
	KEY_KP_EQUAL 336
	KEY_BACK 4
	KEY_MENU 5
	KEY_VOLUME_UP 24
	KEY_VOLUME_DOWN 25 )
]
